// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AcitonBar: typeof import('./src/components/AcitonBar.vue')['default']
    DarkSwitch: typeof import('./src/components/DarkSwitch.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    TimeDial: typeof import('./src/components/TimeDial.vue')['default']
    TimeSchedule: typeof import('./src/components/TimeSchedule.vue')['default']
    TimezoneItem: typeof import('./src/components/TimezoneItem.vue')['default']
    TimezoneSearch: typeof import('./src/components/TimezoneSearch.vue')['default']
  }
}

export {}
